FROM python:3.13-slim

WORKDIR /app
COPY . .
RUN pip install --no-cache-dir .[s3] \
                               apache-airflow==3.1.8 \
                               apache-airflow-providers-amazon[s3fs]
